name: Publish to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn build
      - run: npm run publishOnly
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
